### ISSUE TITLE
Can't resolve './index' in 'node_modules/vue-flawless-modal/src'

### ISSUE THREAD

**Issue by ermilov** [Kelin2025/vue-flawless-modal#1]
Failed to compile.

./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/username/www/project/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-flawless-modal/src/ModalWindow.vue
Module not found: Error: Can't resolve './index' in '/Users/username/www/project/node_modules/vue-flawless-modal/src'
 @ ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/username/www/project/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-flawless-modal/src/ModalWindow.vue 27:0-32
 @ ./node_modules/vue-flawless-modal/src/ModalWindow.vue
 @ ./node_modules/vue-flawless-modal/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

**Comment by Kelin2025** [comment]
It should work now (2569a3ad3b4069d2ea731ac334f0cfe52ab3352a)
